chore: bump node version in workflows to `16.13.0` (#313)
This is required to fix build errors like:

```console
Error: Cannot find module 'node:stream'
Require stack:
- /home/runner/work/cdk8s-core/cdk8s-core/node_modules/jsii-rosetta/lib/json.js
- /home/runner/work/cdk8s-core/cdk8s-core/node_modules/jsii-rosetta/lib/tablets/tablets.js
```

Which are currently failing all our dependency upgrades because `jsii-rosetta` makes use of new API not available in 14.17.0