fix: bump TypeScript to ~5.9
The `constructs` library now uses a TypeScript 5 feature, so all
projects that consume it must be bumped from TS 4 -> TS 5 as well,
like cdk8s.

Solves:

```
node_modules/constructs/lib/index.d.ts(2,1): error TS1383: Only named exports may use 'export type'.
```

Signed-off-by: Rico Huijbers <rix0rrr@gmail.com>